name: Build APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ติดตั้ง Android SDK + ยอมรับไลเซนส์
      - uses: android-actions/setup-android@v3
      - run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - run: chmod +x gradlew
      - run: ./gradlew --no-daemon :app:assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
